[project]
server = 'localhost'
# server = 'host.docker.internal'
username = 'admin'
password = 'admin'
root = 'c:\Datacert'

[environment]
name = 'local dev'
passport_version = '18.2'
cp_enabled = 'false'
